name: Run Python Project

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Разрешения на запись и редактирование содержимого

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask requests pyyaml scikit-learn opencv-python-headless

    - name: Check directory structure
      run: |
        echo "Current directory structure before running script:"
        ls -R

    - name: Run server script
      run: python tester.py

    - name: Check directory structure after script
      run: |
        echo "Current directory structure after running script:"
        ls -R
