name: Run Python Project

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask
        python -m pip install requests
        python -m pip install pyyaml
    
    # Добавляем шаг для установки прав доступа
    - name: Set permissions
      run: chmod -R 755 /home/runner/work/Site_Project/Site_Project
      
    # Запускаем серверный скрипт
    - name: Run server script
      run: python tester.py
